### ISSUE TITLE
Redesign architecture for simulator

### ISSUE THREAD

**Issue by cyderize** [MARIE-js/MARIE.js#53]
A new architecture would be useful:
- Enable an extensible method of using more instructions
  - Enable users to input RTL to add their own instructions
- Enable the use of more registers
- Ensure that the hexadecimal representations are still easily read - i.e. try to keep to 4-bit groups
- E.g. use 6-bits for instructions, 2-bits for registers, 8-bits for operands?

**Comment by lorderikir** [comment]
Current Structure: 4 bits opcode and 12 bit instruction (since there's only 1 GPR)
- 2^4 or 16 instructions
- 2^12 or 4096 addresses

We can increase opcode to 6 bits, 2bits for the register and 8 bits for memory
- 2^6 or 64 instructions
- 2 General Purpose Registers
- 2^8 or 256 addresses for memory

which is a change of:
- 48 more instructions (flexible)
- 3840 less addresses for memory (which we don't use much anyways)
- And 1 more GPR which would increase flexibility of the Machine Assembly Language

**Comment by cyderize** [comment]
Suggestion:

24-bit words: 8-bits for instructions, 4-bits for general purpose registers, 12-bits for addresses.

**Comment by jos0003** [comment]
We'll keep the original architecture of MARIE as it is. 

But we can implement an extended mode which adds three general registers to a separate register bank (with its own two control read and two control write wires), and extend the instruction opcode part of the instruction from 4 bits to 8 bits.

As for @cyderize's suggestion, the original architecture does not have the ability to reference registers (it only allows you to reference memory cells, which is reasonable considering that AC is the only GPR). As we have multiple GPRs in extended mode, we need to be able to reference which register we want to transfer data to and from memory in an instruction. For example, `Load GPR2, x` loads the memory value stored at address x into register GPR2.

Here is a list of registers with their own reference number:
- `0` - AC
- `1` - GPR2
- `2` - GPR3
- `3` - GPR4

If we want to implement the `mov` instruction, we need to use 2 bits for the source register, and 2 bits for the destination register. While this is great, we would have to represent the instruction in a slightly different way (i.e., instead of 0x000000, we could have 0x00[0][0]000, where the number in the bracket is a reference to a GPR). I guess this is good for explaining how to compute the final hexadecimal value from `LO` and `HI` values with bit shifting involved. `final_value = (src_reg << 2) + dest_reg`

In addition to more GPRs, we have 12 bits of instruction opcode space to work with. This means we have 256 possible instructions, and by maintaining the original instruction set we have 256 - 15 = 241 instructions left to work with. For now, we'll just allow the user to implement their own instructions using RTL notation. This is also a good way to illustrate the fact that processors use microprogrammable logic instead of hardwired logic.

Users should be able to enable extended mode for specific files in the preferences. If this is enabled, then users are recommended to export their files in JSON format (maybe we can have a special file extension called `.masx`?). If they choose to export their file in `.mas` format whilst in extended mode, they'll lose their defined instructions, and they will have to manually switch to extended mode later on if they decide to re-import the file (or we could auto-detect the file for the slightly different instruction format and prompt them if they want to switch to extended mode?).

**Comment by lorderikir** [comment]
The structure of *.mas can be redesigned e.g. the code can look like

```
.mode=extended
.registers={move1,GPR1←GPR3}

Load X,gpr1
Store X,gpr2
```

**Comment by auroranil** [comment]
Closing this issue due to it being stale.
